services:


  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data:Z
      - caddy_config:/config:Z
    environment:
      - CLOUDFLARE_API_TOKEN=my_not_public_token
    networks:
      - my-network

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    user: "65534:65534"
    volumes:
      - ./vaultwarden-data:/data:Z
    environment:
      ROCKET_PORT: 1111
      ROCKET_ADDRESS: 0.0.0.0
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
