#  /docker-compose/docker-compose.yml

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /vw-data:/data

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    # map Caddyfile to its location on host
      - /docker-compose/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  radicale:
      image: ghcr.io/kozea/radicale:3.5.10
      container_name: radicale
      ports:
      - 5232:5232
      volumes:
        - config:/etc/radicale
        - data:/var/lib/radicale

volumes:
  caddy_data:
  caddy_config:

  config:
    name: radicale-config
    driver: local
    driver_opts:
      type: none
      o: bind
      # map dir to its location on host
      device: /docker-compose/radicale/config

  data:
    name: radicale-data
    driver: local
    driver_opts:
      type: none
      o: bind
      # map dir to its location on host
      device: /docker-compose/radicale/data