
- hosts: alma
  become: yes
  
  vars_files:
    - secrets.yml
    - vars.yml

  tasks:
    - name: Find AlmaLinux repo files
      find:
        paths: /etc/yum.repos.d
        patterns: 'almalinux*.repo'
      register: alma_repos
      become: true

    - name: Disable mirrorlist
      replace:
        path: "{{ item.path }}"
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      loop: "{{ alma_repos.files }}"
      become: true

    - name: Enable baseurl
      replace:
        path: "{{ item.path }}"
        regexp: '^# *baseurl='
        replace: 'baseurl='
      loop: "{{ alma_repos.files }}"
      become: true

    # Update package metadata
    - name: Update package metadata
      dnf:
        update_cache: yes

    # Create parent dir
    - name: Create main directory
      file:
        path: /{{ parent_dir }}
        state: directory

    # Check if cloudflared is inatalled
    - name: Check if cloudflared is already installed
      stat:
        path: /etc/systemd/system/cloudflared.service
      register: cloudflared_service
      when: env == "cloudflared"

    # Install cloudflared if not
    - name: Add cloudflare repo
      get_url:
        url: https://pkg.cloudflare.com/cloudflared.repo
        dest: /etc/yum.repos.d/cloudflared.repo
        mode: '0644'
      when:
        - not cloudflared_service.stat.exists
        - env == "cloudflared"
  
    - name: Install cloudflared
      dnf: 
        name: cloudflared
        state: present
      when:
        - not cloudflared_service.stat.exists
        - env == "cloudflared"

    - name: Install cloudflared service with token
      command: cloudflared service install {{ cloudflare_install_token }}
      when:
        - not cloudflared_service.stat.exists
        - env == "cloudflared"

    #----   PODMAN   ----#
    
    - name: Ensure my-network exists
      containers.podman.podman_network:
        name: my-network
        state: present
        
    - name: Run Caddy role
      import_role:
        name: caddy

    - name: Run Vaultwarden role
      import_role:
        name: vaultwarden

    - name: Run Tandoor role
      import_role:
        name: tandoor

    - name: Run Mosquitto role
      import_role:
        name: mosquitto
        
    - name: Run InfluxDB role
      import_role:
        name: influxdb
        
    - name: Run Grafana role
      import_role:
        name: grafana

    - name: Run Telegraf role
      import_role:
        name: telegraf
