[agent]
  interval = "1s"
  round_interval = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors/#"]
  qos = 0
  connection_timeout = "30"
  data_format = "value"
  data_type = "float"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "token"
  organization = "myorg"
  bucket = "sensors"
