{
 "title": "Sensor Data",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/humidity\")\r\n  |> filter(fn: (r) => r._value >= 30)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/humidity\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r._value >= 30)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -72h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/humidity\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r._value >= 30)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/temperature\")\r\n  |> filter(fn: (r) => r._value >= 15)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/temperature\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r._value >= 15)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -72h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/temperature\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r._value >= 15)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    }
   ]
  },
  {
   "title": "Soil Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/soil\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/soil\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -120h)\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r.topic == \"sensors/soil\")\r\n  |> aggregateWindow(every: 60m, fn: mean, createEmpty: false)\r\n  |> filter(fn: (r) => r[\"host\"] == \"prod\")\r\n"
    }
   ]
  }
 ]
}