    # Mosquitto
    - name: Copy mosquitto.conf
      copy:
        src: "{{ mosquitto_conf }}"
        dest: /{{ parent_dir }}/{{ mosquitto_conf }}
        mode: "{{ mosquitto_file_permissions }}"

    - name: Open port for Mosquitto
      firewalld:
        port: "{{ mosquitto_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Deploy Mosquitto Quadlet
      ansible.builtin.template:
        src: mosquitto.container.j2
        dest: /etc/containers/systemd/mosquitto.container
        mode: '{{ mosquitto_container_permissions }}'

    - name: Start Mosquitto
      ansible.builtin.systemd:
        name: mosquitto.service
        state: started
        daemon_reload: true
