    - name: Render telegraf.conf
      template:
        src: "{{ telegraf_conf }}.j2"
        dest: /{{ parent_dir }}/{{ telegraf_conf }}
        mode: "{{ telegraf_file_permissions }}"

    - name: Wait for Mosquitto port
      wait_for:
        host: 127.0.0.1
        port: "{{ mosquitto_port }}"
        delay: 2
        timeout: 30

    - name: Deploy Telegraf Quadlet
      ansible.builtin.template:
        src: telegraf.container.j2
        dest: /etc/containers/systemd/telegraf.container
        mode: '{{ telegraf_container_permissions }}'

    - name: Start Telegraf
      ansible.builtin.systemd:
        name: telegraf.service
        state: started
        daemon_reload: true
